name: Pylint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pylint
    - name: Analysing the code with pylint
      run: |
        exit_code=$(pylint `ls -R|grep .py$|xargs`)
        echo "Exit code: $exit_code"
        exit 0
