# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test setup.py

on:
  push:
    paths:
      - "setup.py"
  pull_request:
    paths:
      - "setup.py"
  schedule:
    - cron: '25 8 * * 5'
  workflow_dispatch:

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run setup.py
      run: python setup.py
  
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run setup.py
      run: sudo python setup.py
    
    - name: Test if command exists
      run: type crocrodile
